//! Golden-vector fixtures (test-only): loaders for the reference
//! input/output files under `test-data/iq/`, generated by the original
//! C converters — see `test-data/README.md` for provenance (the MIT
//! revision of `airspyone_host`) and format.

use std::path::PathBuf;

/// The committed scenarios.
pub(crate) const SCENARIOS: [&str; 4] = ["impulse", "dc", "tone", "noise"];

/// One scenario's fixture set.
pub(crate) struct Vectors {
    /// Raw 12-bit ADC words.
    pub(crate) input: Vec<u16>,
    /// `iqconverter_int16_process` reference output (in-place buffer,
    /// three 2048-sample blocks concatenated).
    pub(crate) int16: Vec<i16>,
    /// `iqconverter_float_process` reference output, decoded from the
    /// exact IEEE-754 bit patterns.
    pub(crate) float: Vec<f32>,
}

fn vector_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../test-data/iq")
}

fn read_lines(name: &str, kind: &str) -> Vec<String> {
    let path = vector_dir().join(format!("{name}.{kind}.txt"));
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| unreachable!("fixture {} unreadable: {e}", path.display()));
    text.lines().map(str::to_owned).collect()
}

fn parse_all<T>(name: &str, kind: &str, parse: impl Fn(&str) -> Option<T>) -> Vec<T> {
    read_lines(name, kind)
        .iter()
        .enumerate()
        .map(|(i, line)| {
            parse(line)
                .unwrap_or_else(|| unreachable!("{name}.{kind} line {}: bad value {line:?}", i + 1))
        })
        .collect()
}

/// Load one scenario's three fixture files, panicking (test context)
/// on any malformed line.
pub(crate) fn load_scenario(name: &str) -> Vectors {
    Vectors {
        input: parse_all(name, "input", |l| l.parse().ok()),
        int16: parse_all(name, "int16", |l| l.parse().ok()),
        float: parse_all(name, "float", |l| {
            u32::from_str_radix(l, 16).ok().map(f32::from_bits)
        }),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn all_scenarios_load_with_expected_shape() {
        for name in SCENARIOS {
            let v = load_scenario(name);
            assert_eq!(v.input.len(), 6144, "{name} input");
            assert_eq!(v.int16.len(), 6144, "{name} int16");
            assert_eq!(v.float.len(), 6144, "{name} float");
            assert!(v.input.iter().all(|&w| w <= 4095), "{name}: 12-bit range");
        }
    }

    #[test]
    fn scenario_contents_match_their_definitions() {
        let impulse = load_scenario("impulse");
        assert_eq!(impulse.input[100], 4095);
        assert!(
            impulse
                .input
                .iter()
                .enumerate()
                .all(|(i, &w)| i == 100 || w == 2048)
        );

        let dc = load_scenario("dc");
        assert!(dc.input.iter().all(|&w| w == 3072));

        // LCG: first word = ((0x12345678 * 1664525 + 1013904223) >> 20) & 0xFFF
        let noise = load_scenario("noise");
        let first = 0x1234_5678u32
            .wrapping_mul(1_664_525)
            .wrapping_add(1_013_904_223)
            >> 20;
        assert_eq!(u32::from(noise.input[0]), first);
    }

    #[test]
    fn float_bits_decode_to_finite_values() {
        for name in SCENARIOS {
            let v = load_scenario(name);
            assert!(
                v.float.iter().all(|f| f.is_finite()),
                "{name}: reference floats must be finite"
            );
        }
    }
}
