//! Golden-vector fixtures (test-only): loaders for the reference
//! input/output files under `test-data/iq/`, generated by the original
//! C converters — see `test-data/README.md` for provenance (the MIT
//! revision of `airspyone_host`) and format.

use std::path::PathBuf;

/// The committed scenarios.
pub(crate) const SCENARIOS: [&str; 4] = ["impulse", "dc", "tone", "noise"];

// Fixture-specification constants — the generation contract documented
// in test-data/README.md (harness values, not C transcriptions).
/// Three sequential 2048-sample process calls per scenario.
pub(crate) const VECTOR_LEN: usize = 6144;
/// 12-bit ADC full scale.
const ADC_MAX: u16 = 4095;
/// 12-bit ADC mid scale (zero level).
const ADC_MID: u16 = 2048;
/// The impulse scenario's spike position.
const IMPULSE_INDEX: usize = 100;
/// The dc scenario's constant word (+0.5 FS).
const DC_WORD: u16 = 3072;
/// The tone scenario's period in samples (fs/16 sine).
const TONE_PERIOD: usize = 16;
/// Tone amplitude from the fixture contract in test-data/README.md.
const TONE_AMPLITUDE: u16 = 1024;
/// The complete quantized tone period — `lround(2048 + 1024·sin(2πk/16))`
/// per the generation contract in test-data/README.md.
const TONE_EXPECTED: [u16; TONE_PERIOD] = [
    2048, 2440, 2772, 2994, 3072, 2994, 2772, 2440, 2048, 1656, 1324, 1102, 1024, 1102, 1324, 1656,
];
/// Noise LCG (numerical-recipes constants), seed, and 12-bit take.
const LCG_MULT: u32 = 1_664_525;
const LCG_INC: u32 = 1_013_904_223;
const LCG_SEED: u32 = 0x1234_5678;
const LCG_SHIFT: u32 = 20;

/// One scenario's fixture set.
pub(crate) struct Vectors {
    /// Raw 12-bit ADC words.
    pub(crate) input: Vec<u16>,
    /// `iqconverter_int16_process` reference output (in-place buffer,
    /// three 2048-sample blocks concatenated).
    pub(crate) int16: Vec<i16>,
    /// `iqconverter_float_process` reference output, decoded from the
    /// exact IEEE-754 bit patterns.
    pub(crate) float: Vec<f32>,
}

fn vector_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../test-data/iq")
}

// `unreachable!` (not `panic!`) throughout: committed fixtures failing
// to parse means the repository itself is broken, and `clippy::panic`
// is denied workspace-wide.
fn parse_all<T>(name: &str, kind: &str, parse: impl Fn(&str) -> Option<T>) -> Vec<T> {
    let path = vector_dir().join(format!("{name}.{kind}.txt"));
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| unreachable!("fixture {} unreadable: {e}", path.display()));
    text.lines()
        .enumerate()
        .map(|(i, line)| {
            parse(line)
                .unwrap_or_else(|| unreachable!("{name}.{kind} line {}: bad value {line:?}", i + 1))
        })
        .collect()
}

/// Load one scenario's three fixture files, panicking (test context)
/// on any malformed line.
pub(crate) fn load_scenario(name: &str) -> Vectors {
    Vectors {
        input: parse_all(name, "input", |l| l.parse().ok()),
        int16: parse_all(name, "int16", |l| l.parse().ok()),
        float: parse_all(name, "float", |l| {
            u32::from_str_radix(l, 16).ok().map(f32::from_bits)
        }),
    }
}

#[cfg(test)]
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn all_scenarios_load_with_expected_shape() {
        for name in SCENARIOS {
            let v = load_scenario(name);
            assert_eq!(v.input.len(), VECTOR_LEN, "{name} input");
            assert_eq!(v.int16.len(), VECTOR_LEN, "{name} int16");
            assert_eq!(v.float.len(), VECTOR_LEN, "{name} float");
            assert!(
                v.input.iter().all(|&w| w <= ADC_MAX),
                "{name}: 12-bit range"
            );
        }
    }

    #[test]
    fn scenario_contents_match_their_definitions() {
        let impulse = load_scenario("impulse");
        assert_eq!(impulse.input[IMPULSE_INDEX], ADC_MAX);
        assert!(
            impulse
                .input
                .iter()
                .enumerate()
                .all(|(i, &w)| i == IMPULSE_INDEX || w == ADC_MID)
        );

        let dc = load_scenario("dc");
        assert!(dc.input.iter().all(|&w| w == DC_WORD));

        // The full noise sequence recomputed from the LCG spec.
        let noise = load_scenario("noise");
        let mut s = LCG_SEED;
        for (i, &w) in noise.input.iter().enumerate() {
            s = s.wrapping_mul(LCG_MULT).wrapping_add(LCG_INC);
            assert_eq!(u32::from(w), s >> LCG_SHIFT, "noise word {i}");
        }

        // Tone: every sample checked against the documented 16-value
        // period, plus the landmark phases spelled out.
        let tone = load_scenario("tone");
        for (i, &w) in tone.input.iter().enumerate() {
            assert_eq!(w, TONE_EXPECTED[i % TONE_PERIOD], "tone sample {i}");
        }
        assert_eq!(tone.input[0], ADC_MID);
        assert_eq!(tone.input[TONE_PERIOD / 4], ADC_MID + TONE_AMPLITUDE);
        assert_eq!(tone.input[3 * TONE_PERIOD / 4], ADC_MID - TONE_AMPLITUDE);
    }

    #[test]
    fn float_bits_decode_to_finite_values() {
        for name in SCENARIOS {
            let v = load_scenario(name);
            assert!(
                v.float.iter().all(|f| f.is_finite()),
                "{name}: reference floats must be finite"
            );
        }
    }
}
